***PROBLEM 3.16;
DATA ASPIRIN;
	INPUT GROUP $ RESULT $ STROKECOUNT;

DATALINES;
ASPIRIN YES 65
ASPIRIN NO 935
PLACEBO YES 165
PLACEBO NO 1835
;

PROC FREQ DATA=ASPIRIN;
	TITLE "PROBLEM 3.16";
	TABLES GROUP*RESULT/CHISQ;
	WEIGHT STROKECOUNT;
RUN;