***PROBLEM 3.2;
PROC FORMAT;
	VALUE GENDER 1="MALE" 2="FEMALE";
	VALUE $SES "L"="LOW" "M"="MEDIUM" "H"="HIGH";
	VALUE AGEGROUP LOW-20="<=20" 21-40="21 TO 40" 41-HIGH=">=41";
RUN;

DATA QUES2;
	INPUT ID $ GENDER SES $ DRUG $ AGE;
	FORMAT GENDER GENDER. SES $SES.;
	LABEL SES="SOCIOECONOMIC STATUS" DRUG="DRUG GROUP" AGE="AGE OF SUBJECT";
	IF DRUG="A" OR DRUG="C" OR DRUG="F" OR DRUG="B" THEN COST="LOW";
	ELSE IF DRUG NE " " THEN COST="HIGH";
	
DATALINES;
001 1   L B 15
002 2 M    Z   35
003    2 H  F 76
004 1 L C 21
005 2 H . 58
;

PROC PRINT DATA=QUES2;
	TITLE "PROBLEM 3.2";
RUN;

PROC FREQ DATA=QUES2;
	TITLE "PROBLEM 3.2 FREQUENCY";
	LABEL COST="COST";
	TABLES SES COST AGE;
	FORMAT AGE AGEGROUP.;
RUN;
	
	
