***PROBLEM 3.4A;
DATA BLOODDATA;
	SET BLOOD;
	LENGTH WBCGRP $ 15;

	IF WBC GE 3000 AND WBC LE 4000 THEN WBCGRP="LOW";
	ELSE IF WBC GE 4001 AND WBC LE 6000 THEN WBCGRP="MEDIUM";
	ELSE IF WBC GE 6001 AND WBC LE 12000 THEN WBCGRP="HIGH";
	ELSE IF WBC LT 3000 AND WBC NE " " THEN WBCGRP="ABNORMALLY LOW";
	ELSE IF WBC GT 12000 THEN WBCGRP="ABNORMALLY HIGH";
	ELSE WBCGRP="NOT AVAILABLE";
RUN;

PROC FREQ DATA=BLOODDATA;
	TITLE "PROBLEM 3.4A";
	TABLES WBCGRP/MISSING NOCUM;
RUN;