***PROBLEM 4.10;
PROC MEANS DATA=CLINICAL;
	CLASS GENDER GROUP;
	VAR WEIGHT;
	OUTPUT OUT=SUMMARY_PROB4_10
		MEAN=
		MEDIAN=
		STDDEV= / AUTONAME;
RUN;

PROC PRINT DATA=SUMMARY_PROB4_10;
	TITLE "PROBLEM 4.10";
RUN;