***PROBLEM 4.2;
DATA AGES;
	SET ABC_CORP;
	AGE_ACTUAL=YRDIF(DOB,"15JAN2005"D,"ACTUAL");
	AGE_TODAY=ROUND(YRDIF(DOB,TODAY(),"ACTUAL"),.1);
	AGE=INT(YRDIF(DOB,VISIT_DATE,"ACTUAL"));
RUN;
PROC PRINT DATA=AGES;
	TITLE "PROBLEM 4.2";
	FORMAT DOB ddmmyy10. VISIT_DATE mmddyy8.
RUN;