***PROBLEM 4.8;
PROC MEANS DATA=CLINICAL;
	CLASS PATIENT;
	VAR WEIGHT;
	OUTPUT OUT=SUMMARY_PROB4_8(DROP=_TYPE_)
		MEAN=
		MEDIAN=
		MIN=
		MAX= / AUTONAME;
RUN;
PROC PRINT DATA=SUMMARY_PROB4_8;
	TITLE "PROBLEM 4.8";
RUN;