***ADDITIONAL PROBLEM;
DATA ADDITIONAL;
	INPUT ADULT CHILDREN;
	DATE=TODAY();
	TOTAL=30*ADULT+15*CHILDREN;
	
	
	IF WEEKDAY(DATE) EQ 2 THEN TOTAL=TOTAL-(TOTAL*.3);
	IF WEEKDAY(DATE) EQ 1 OR WEEKDAY(DATE) EQ 7 THEN TOTAL=TOTAL+(TOTAL*.2);
	
	FORMAT DATE MMDDYY10.;
	FORMAT TOTAL DOLLAR9.2;
	
DATALINES;
2 3
;

RUN;

PROC PRINT DATA=ADDITIONAL;
	TITLE "ADDITIONAL PROBLEM";
	VAR DATE ADULT CHILDREN TOTAL;
RUN;

